require('go').setup({
    disable_defaults = false,
    go = 'go',
    goimports = 'gopls',
    gofmt = 'gopls',
    max_line_len = 0,
    tag_transform = false,
    tag_options = 'json=omitempty',
    gotests_template = "",
    gotests_template_dir = "",
    comment_placeholder = ' 󰟓  ',
    icons = {breakpoint = '', currentpos = ''},
    verbose = false,
    lsp_cfg = false,
    lsp_gofumpt = true,
    lsp_on_attach = nil,
    lsp_keymaps = true,
    lsp_codelens = true,
    lsp_document_formatting = true,
    lsp_inlay_hints = {
        enable = true,
        style = 'eol',
        only_current_line = false,
        only_current_line_autocmd = "CursorHold",
        show_variable_name = true,
        parameter_hints_prefix = " ",
        show_parameter_hints = true,
        other_hints_prefix = "=> ",
        max_len_align = false,
        max_len_align_padding = 1,
        right_align = false,
        right_align_padding = 6,
        highlight = "Comment",
    },
    gopls_remote_auto = true,
    gocoverage_sign = "█",
    dap_debug = true,
    dap_debug_keymap = true,
    dap_debug_gui = true,
    dap_debug_vt = true,
    build_tags = "",
    textobjects = true,
    test_runner = 'go',
    verbose_tests = true,
    run_in_floaterm = false,
    trouble = false,
    test_efm = false,
    luasnip = false,
})


